#!/usr/bin/env perl
use strict;
use warnings;
use POSIX;
use IPC::Run qw(run);

# Print help
if ($#ARGV + 1 != 1) {
  print "\nUsage: ./fingerprint sample.xml\n"; exit;
}

# Get input file
my $filename = $ARGV[0];
open(my $fh, '<:encoding(UTF-8)', $filename) or die "Could not open file '$filename' $!";

# Extract source certificate
my $source;
while (my $row = <$fh>) {
  chomp $row;
  if($row =~ /<dsig:X509Certificate>(.*)<\/dsig:X509Certificate>/){
    $source = $1
  }
}

# Create OpenSSL compatible certificate string
my $cert = "-----BEGIN CERTIFICATE-----";
for (my $i = 0; $i <= floor((length $source)/64); $i++) {
    $cert = $cert . "\n" . substr $source, ($i*64), 64;
}
$cert = $cert . "-----END CERTIFICATE-----\n";

# Pipe the certificate to OpenSSL to get the SHA1 fingerprint
my $output;
run["openssl", "x509", "-noout", "-fingerprint", "-sha1"], \$cert, \$output, \$output;

print $output;
